repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.4
  hooks:
  - id: clang-format
    args: [-Werror]  # change formatting warnings to errors, hook includes -i (Inplace edit) by default
    types_or: [c++, c]  # override default file types to only C and CPP files
    exclude: '^upgrade/|^scripts/'  # don't run on scripts/ and upgrade/

- repo: https://github.com/perigoso/pre-commit-hooks
  rev: v0.2
  hooks:
  - id: check-hex-case
    args: [--lower-digits] # edit-in-place, hex number digits to lower case (defaults to upper case), i.e. 0x55aa
