exclude: '^upgrade/|^scripts/'  # don't run hooks on scripts/ and upgrade/

repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.2
  hooks:
  - id: clang-format
    args: [-Werror]  # change formatting warnings to errors, hook includes -i (Inplace edit) by default
    types_or: [c++, c]  # override default file types to only C and CPP files

- repo: https://github.com/perigoso/pre-commit-hooks
  rev: v0.2
  hooks:
  - id: check-hex-case
    args: [--lower-digits] # edit-in-place, hex number digits to lower case (defaults to upper case), i.e. 0x55aa

  - id: check-accidental-assignment
    args: [--strict, --skip-keywords, DO_PRAGMA, --] # strict, check in all parentheses found, skip check in DO_PRAGMA macro
    # FIXME: Known assignment in find_debuggers, needs large refactoring, ignore file temporarily so we get a working check for the rest of the code base
    exclude: '^src/platforms/hosted/bmp_serial.c'
