[constants]
compileFlags = ['--sysroot', '/usr/x86_64-w64-mingw32ucrt']
linkFlags = ['--sysroot', '/usr/x86_64-w64-mingw32ucrt']

[binaries]
c = 'x86_64-w64-mingw32ucrt-gcc'
cpp = 'x86_64-w64-mingw32ucrt-g++'
# c_ld = 'x86_64-w64-mingw32ucrt-ld.bdf'
# cpp_ld = 'x86_64-w64-mingw32ucrt-ld.bdf'
ar = 'x86_64-w64-mingw32ucrt-ar'
as = 'x86_64-w64-mingw32ucrt-as'
rc = 'x86_64-w64-mingw32ucrt-rc'
windres = 'x86_64-w64-mingw32ucrt-windres'
strip = 'x86_64-w64-mingw32ucrt-strip'
objcopy = 'x86_64-w64-mingw32ucrt-objcopy'
objdump = 'x86_64-w64-mingw32ucrt-objdump'
size = 'x86_64-w64-mingw32ucrt-size'
cmake = 'false'
exe_wrapper = 'wine'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = compileFlags
cpp_args = compileFlags
c_link_args = linkFlags
cpp_link_args = linkFlags

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'amd64'
endian = 'little'
